### ISSUE TITLE
Verifier sends GET request 'body' as query string and request 'query' as query string 

### ISSUE THREAD

**Issue by sankalan-sharechat** [pact-foundation/pact-node#199] opened 2019-11-25 12:24 UTC
## Software versions

-   **OS**:  Mac OS Mojave 10.14.5
-   **Library version**: e.g. 10.2.2
-   **Node Version**: v12.12.0

## Expected behaviour

When GET request is sent with a body, it should be received as a body when using the verifier.
When GET request is sent with a query, it should be received as a query when using the verifier. 

## Actual behaviour

In both the cases, GET request is sent as a query string and code validations for receiving body schema fails. 

## Steps to reproduce

Here is my pactfile. The issue is fairly simple to reproduce. I cannot use the query string because I would have to change a lot of APIs which is not doable, the only way out for me from this is to use it as a body or write a middleware that intercepts the GET request with the query string, removes the query string and create a body and then use that to proceed forward. I don't think this is a good idea provided that we have a body field and a query field in our pact file which serves two different purpose. 

```{
  "consumer": {
    "name": "UserService"
  },
  "provider": {
    "name": "AccountService"
  },
  "interactions": [
    {
      "description": "a request to retrieve user account data",
      "providerState": "it has one user",
      "request": {
        "method": "GET",
        "path": "/account-service/v1.0.0/getAccountInfo",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "userId": "6796fc82-ebac-4afd-8498-a963e7cf8fdf"
        }
      },
      "response": {
        "status": 200,
        "headers": {
        },
        "body": {
          "phoneNo": 919455334525,
          "countryAreaCode": 91
        }
      },
      "metadata": null
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}```

## Relevant log files

```{"service":"account-service","err":"{\"stack\":\"Error: invalid getAccountInfoSchema data, err: ValidationError: child \\\"userId\\\" fails because [\\\"userId\\\" is required]\\n    at GetAccountInfo.schemaValidator [as validate] (/Users/SankalanParajuli/repos/bharat11-account-service/models/index.js:22:9)\\n    

getAccountInfoSchema data, err: ValidationError: child \\\"userId\\\" fails because [\\\"userId\\\" is required]\"}","path":"/getAccountInfo","event":{},"level":"error","message":"Error while verifying old token"}
GET /account-service/v1.0.0/getAccountInfo?%7B%22userId%22%3A%226796fc82-ebac-4afd-8498-a963e7cf8fdf%22%7D 400 1.029 ms - 37```

**Comment by TimothyJones** [comment] 2019-11-26 00:05
I've hit this before - the problem is that HTTP GET requests aren't expected to have bodies.

 > A payload within a GET request message has no defined semantics;
 sending a payload body on a GET request might cause some existing
 implementations to reject the request.  - [RFC 7231 4.3.1](https://tools.ietf.org/html/rfc7231#section-4.3.1)

This means that many HTTP libraries (including the ones that Pact is backed by) don't handle GET requests with a body in a predictable way. 

See [this stackoverflow question](https://stackoverflow.com/questions/978061/http-get-with-request-body) for some discussion. The spec used to explicitly forbid bodies in GET requests. In the current version (quoted above), bodies are no longer forbidden, but the behaviour is not defined (and the request may be rejected).

I can see an argument for "I know it's off-spec, but I'd like to be able to mock this request anyway". The challenge is that I'm not sure how we'd go about making a consistent implementation for off-spec behaviour that works across all platforms.

Probably Pact should produce a warning in this case.

**Comment by sankalan-sharechat** [comment] 2019-11-26 04:29
Hi @TimothyJones 
Thanks for the reply! I had read that same stackoverflow question when I was working with REST APIs. But the system I am trying to implement Pact on right now handles all its GET requests using a body. I cannot propose we change all the APIs, is there something I can do as a workaround?

What I have in mind is to implement request filters to intercept the URL and remove the query string. Then I can create a body from that string and send it as a GET request. Do you think this would be a good idea?

I still think having 'query' and 'body' as options for addInteraction in Pact should be implemented such that body should be used to send body. 

@mefellows any chance we can look into implementing this?

**Comment by TimothyJones** [comment] 2019-11-27 00:27
> I still think having 'query' and 'body' as options for addInteraction in Pact should be implemented such that body should be used to send body.

I think this is actually the "fault" of the underlying http library used to send the verification, rather than something Pact does explicitly. I don't think we can expect the library to violate or ignore the HTTP spec.

**Comment by TimothyJones** [comment] 2019-12-10 00:23
> What I have in mind is to implement request filters to intercept the URL and remove the query string. Then I can create a body from that string and send it as a GET request. Do you think this would be a good idea?

Largely, I think that encouraging the provider to follow the HTTP spec is by far the best solution. Maybe at the moment, Pact is the only thing that is hitting this problem, but that may not be true in the future.

Since you say that option isn't available, then I think your workaround sounds ok. I would want to constrain the workaround so that it affects as little as possible, and I think your solution does that.

I do want to stress that I think encouraging the provider to follow the spec is a much much more preferable solution.

I'll close this issue for now - please feel free to reopen if you have further trouble.

**Closed by TimothyJones** 2019-12-10 00:24 UTC
Labels: question
