### ISSUE TITLE
Mock Server not Starting

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/pact-node#48] opened 2017-10-07 20:07 UTC
I'm currently trying to set up pact with an Angular application and Karma. When running the karma test in which the pact is generated, I always get the error "process not found":

```
Error: Command failed: taskkill /f /t /pid 13344
FEHLER: Der Prozess "13344" wurde nicht gefunden.

    at checkExecSyncError (child_process.js:472:13)
    at Object.execSync (child_process.js:512:13)
    at Server.stop (C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-node\src\server.js:138:7)
    at Server.<anonymous> (C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-node\src\server.js:117:8)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
```

After some digging, I realized this is just a subsequent error to the mock server not starting. With LOGLEVEL set to DEBUG, I get the following log output before the above:

```
[2017-10-07T14:40:44.300Z] DEBUG: pact-node@4.12.0/14532 on THEMACHINE:
    : cannot load such file -- bundler/vendor/molinillo/lib/molinillo/modules/specification_provider (LoadError)
```

So, there are two issues here:
1. When the mock server isn't starting, an error should be raised so that it's clear what went wrong. That would have saved me some trouble finding the real cause, because I was first looking into the "process not found" error :).
2. Why do I get the LoadError? Obviously is has something to do with Ruby dependencies not being satisfied, but I'm not (yet) into Ruby enough to find out what's wrong here.

I have prepared a minimal example at https://github.com/thombergs/pact-node-test. Running `npm run start` I get the above error.

I would appreciate any hints on this issue ;)

**Comment by mboudreau** [comment] 2017-10-08 10:11
Thanks for letting us know. I'll take a look at this tomorrow. Cheers.

**Comment by mefellows** [comment] 2017-10-08 10:14
Could you please let us know the version of `pact`, `pact-node` and `karma-pact` that you're using? This will help us debug it.

I suspect it is a Windows-only bug, but a recent change should have addressed it (or perhaps only a subclass of the problem).

**Comment by thombergs** [comment] 2017-10-08 14:23
Sure. The complete dependencies can be found in my [package-lock.json](https://github.com/thombergs/pact-node-test/blob/master/package-lock.json). But here are the pact dependencies:

```
pact-node: 4.12.0
pact-mock-service: 2.1.0
pact-provider-verifier: 1.4.3
```

karma-pact can't be responsible, since my [minimal example](https://github.com/thombergs/pact-node-test) only works with pact-node.

And yes, I run it on Windows :)

**Comment by mefellows** [comment] 2017-10-10 21:19
Of course, sorry that was a silly question!

Are you able to test out the latest pact-node (`~5.1.0`) to see if this sorts out your issue? We added a fix in the latest upgrade that should have addressed this problem.

**Comment by thombergs** [comment] 2017-10-11 18:42
When running `npm install` I now get the following:

```
C:\daten\workspaces\pact-node-test>npm install

> @pact-foundation/pact-standalone@1.0.6 postinstall C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-standalone
> node ./src/check-dependencies.js

[2017-10-11T18:39:27.056Z]  INFO: pact-standalone@1.0.6/8776 on THEMACHINE: Checking platform specific dependency for OS 'Windows_NT' and architecture 'x64'...
[2017-10-11T18:39:27.058Z]  INFO: pact-standalone@1.0.6/8776 on THEMACHINE: Platform specific dependency '@pact-foundation/pact-standalone-darwin' installed successf
ully!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @pact-foundation/pact-standalone-linux-x64@1.0.5 (node_modules\@pact-foundation\pact-standalone-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @pact-foundation/pact-standalone-linux-x64@1.0.5: wanted {"os":"linux","arch":"x64"} (current:
 {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @pact-foundation/pact-standalone-linux-ia32@1.0.5 (node_modules\@pact-foundation\pact-standalone-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @pact-foundation/pact-standalone-linux-ia32@1.0.5: wanted {"os":"linux","arch":"ia32"} (curren
t: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @pact-foundation/pact-standalone-darwin@1.0.5 (node_modules\@pact-foundation\pact-standalone\node_modules\@pact-found
ation\pact-standalone-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @pact-foundation/pact-standalone-darwin@1.0.5: wanted {"os":"darwin","arch":"x64,ia32"} (curre
nt: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @pact-foundation/pact-standalone-win32@1.0.5 (node_modules\@pact-foundation\pact-standalone\node_modules\@pact-founda
tion\pact-standalone-win32):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chmod 'C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-standal
one\node_modules\@pact-foundation\pact-standalone-win32\bin\pact-mock-service'

added 12 packages, removed 14 packages and updated 19 packages in 21.524s

C:\daten\workspaces\pact-node-test>npm run test

> pact-node-test@0.0.0 test C:\daten\workspaces\pact-node-test
> echo 'Error: no test specified'

'Error: no test specified'


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


C:\daten\workspaces\pact-node-test>npm run start

> pact-node-test@0.0.0 start C:\daten\workspaces\pact-node-test
> cross-env LOGLEVEL=DEBUG node start-mock-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module '@pact-foundation/pact-standalone-win32'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-standalone\index.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pact-node-test@0.0.0 start: `cross-env LOGLEVEL=DEBUG node start-mock-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pact-node-test@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tom\AppData\Roaming\npm-cache\_logs\2017-10-11T18_40_07_078Z-debug.log

C:\daten\workspaces\pact-node-test>npm install

> dtrace-provider@0.8.5 install C:\daten\workspaces\pact-node-test\node_modules\dtrace-provider
> node scripts/install.js


> @pact-foundation/pact-standalone@1.0.6 postinstall C:\daten\workspaces\pact-node-test\node_modules\@pact-foundation\pact-standalone
> node ./src/check-dependencies.js

[2017-10-11T18:40:54.678Z]  INFO: pact-standalone@1.0.6/10344 on THEMACHINE: Checking platform specific dependency for OS 'Windows_NT' and architecture 'x64'...
[2017-10-11T18:40:54.681Z] ERROR: pact-standalone@1.0.6/10344 on THEMACHINE: Cannot resolve specific pact module for OS Windows_NT' and architecture 'x64'. Download/
install must of failed, please try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pact-foundation/pact-standalone@1.0.6 postinstall: `node ./src/check-dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pact-foundation/pact-standalone@1.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tom\AppData\Roaming\npm-cache\_logs\2017-10-11T18_40_54_945Z-debug.log

```

**Comment by mboudreau** [comment] 2017-10-11 21:08
Do you have a package-lock.json file?

**Comment by mefellows** [comment] 2017-10-11 22:59
He does, it's in the example.

I think it's perhaps an issue with the standalone module. We need to re-instate the Appveyor builds for Windows, else subtle changes will introduce annoying regressions.

**Comment by mefellows** [comment] 2017-10-11 23:03
FWIW that minimal example works totally fine for me (`Darwin localhost 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`).

I did have to remove the `package-lock.json` as it contained a dependency to the windows standalone optional dependency.

We should consider updating our documentation to state that the current recommendation is to _not_ check-in this file, given the open issues with it on npm repo.

**Comment by mboudreau** [comment] 2017-10-11 23:08
@mefellows yeah, could definitely do that.  I've been meaning of solving this by just including all binaries in the pact-standalone because NPM seems to be sitting on their hands with this major bug they introduced.

**Comment by mboudreau** [comment] 2017-10-11 23:12
@thombergs can you check to see if `node_modules/@pact-foundation/pact-standalone-win32` is there?  If not, try deleting `node_modules` and redo `npm install -ddd` to show a silly amount of logs.  Please post that log here so we can decipher where in the process it's failing.  Thanks.

**Comment by thombergs** [comment] 2017-10-12 04:45
`pact-standalone-win32` was missing, as were all `@pact-foundation` dependencies. Probably it didn't get so far to download them.

The log is attached.
[2017-10-12T04_37_46_494Z-debug.log](https://github.com/pact-foundation/pact-node/files/1378074/2017-10-12T04_37_46_494Z-debug.log)

When I remove `package-lock.json` and run `npm install` a second time, the folder `pact-standalone` exists but not the windows variant. I get the following output:

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @pact-foundation/pact-standalone-win32@1.0.5 (node_modules\@pact-foundation\pact-standalone-win32):`

**Comment by mefellows** [comment] 2017-10-12 10:37
Thanks @thombergs.

FWIW I'm having issues locally upgrading `pact` to the latest `5.x.x` branch, very much related to the standalone package (I also can't seem to call `publishPacts`). So there might be multiple things going on here.

**Comment by mboudreau** [comment] 2017-10-12 21:41
@mefellows only on windows?

**Comment by mefellows** [comment] 2017-10-12 21:44
Nope, that was on a Mac. I suspect it was fixed by 183f052007c834b7282135a53f917881ded7efd1 but haven't yet re-tested this (I was looking at a `karma-pact` thingo yesterday when encountering this).

**Comment by mboudreau** [comment] 2017-10-12 23:09
@thombergs I'm looking at the logs and it doesn't seem to even try to download the optional dependencies.  Can you please try again with the same step but without the package-lock.json file?

This is particularly concerning, so I'm looking into it.

**Comment by mboudreau** [comment] 2017-10-12 23:19
@mefellows Can you make sure that the standalone is working correctly?  I'm annoyed with npm optional dependency BS that they're pulling.  I think I'll try packaging all binaries together without restrictions and let node figure it out at runtime which one to use.

**Comment by mboudreau** [comment] 2017-10-13 00:45
@mefellows I've found several things wrong with pact-standalone.  I think a lot of these bugs seems to have been when I updated pact-node to 5.1.0.  I'm fixing them right now, should be out shortly.

**Comment by mefellows** [comment] 2017-10-13 04:33
Yep, looks like some setup issues in `pact-node` and `pact-standalone` that combined with the annoying NPM issue is resulting in this madness.

Thanks for sorting it out.

**Comment by mboudreau** [comment] 2017-10-14 02:08
@mefellows pact standalone packaging issues are now fixed; all binaries are now in the single package and added some tests to make sure we never screw those up again. I'll need to deprecate the old OS specific packages. New version of pact-node released to include these changes.

 @thombergs could you please try it with pact-node 5.1.2 and let us know how you go?  Thanks.

**Comment by mboudreau** [comment] 2017-10-14 03:22
@thombergs I've also updated karma-pact to use the latest version of pact node, version is 2.1.0.  Cheers.

**Comment by thombergs** [comment] 2017-10-14 19:06
I got it to work with the new version, and even through karma-pact now. Thanks a lot for your efforts.

**Comment by mboudreau** [comment] 2017-10-15 00:07
@thombergs that's amazing. Thanks for confirming. I'll close this ticket for now, please let us know if anything else comes up

**Closed by mboudreau** 2017-10-15 00:07 UTC
Labels: triage

**Comment by mefellows** [comment] 2017-10-15 10:16
Thanks so much @mboudreau for all your work on a _bunch_ of stuff this past few days - I encourage anyone to look at the commit history to see this dedication.
