### ISSUE TITLE
cli does not accept git sha for --consumer-version

### ISSUE THREAD

**Issue by travi** [pact-foundation/pact-node#79] opened 2018-03-23 04:01 UTC
instead it enforces semver-style versions: https://github.com/pact-foundation/pact-node/blob/8701b4db9bc5fd50bdc1e02cd076e2fe490a77ea/bin/pact-cli.ts#L58

results in the following error: 
> Error: Invalid value 'd876c1c58dd0f8b8ee50161ffcd83e5c15074e1f' for option --consumer-version.

**Comment by mefellows** [comment] 2018-03-25 04:35
Thanks @travi. In fact, we actively encourage the use of non-semver in the broker so we should definitely allow other schemes here. 

PR welcome ;)

**Comment by mboudreau** [comment] 2018-03-25 06:30
Except, I don't think this is something that pact-node does, but what the
ruby standalone does as part of the publish command.

**Comment by mefellows** [comment] 2018-03-25 07:02
It looks like the regex `/^\d+\.\d+\.\d+$/` in the `pact-cli.ts`, but i'd have to take a look properly.

**Comment by mboudreau** [comment] 2018-03-25 10:27
ah shoot, you're right.  Not sure how that got there....

**Comment by mboudreau** [comment] 2018-03-25 10:58
@travi this has been fixed in 6.12.1.  Cheers.

**Closed by mboudreau** 2018-03-25 10:58 UTC
Labels: good-first-issue, help wanted

**Comment by travi** [comment] 2018-03-25 18:02
thanks a lot guys! that did fix that issue.

with that resolved, i had a little trouble getting the cli command to find my pact files since i expected the input to `--pact-files-or-dirs` to be relative to the root of my project since i was running as an npm script. after trying `./pacts`, `./pacts/pact-file.json`, `pacts`, and `pacts/pact-file.json`, i finally tried an absolute path by using the travis env var `$TRAVIS_BUILD_DIR/pacts/` and that worked.

is it expected that the absolute path is needed, or should i open a separate issue to discuss that behavior further. even if that is intended, a bit of documentation to make that more clear would probably be helpful.

**Comment by mefellows** [comment] 2018-03-25 21:17
I think that's a reasonable ask. The issue is we invoke a cli in another directory so it's relative, just not to what you'd expect. It should be easy enough to do, as long as we allow an absolute path for backwards compatibility.

As a start, documenting this would be good.

**Comment by travi** [comment] 2018-03-25 22:13
> The issue is we invoke a cli in another directory so it's relative, just not to what you'd expect.

i expected something along those lines. 

i opened #80 to track this if you want to make changes for this.
