### ISSUE TITLE
Having an error with finalize()

### ISSUE THREAD

**Issue by lippea** [pact-foundation/pact-node#34] opened 2017-04-27 05:12 UTC
I'm using "pact": "2.2.1" and today I found same code failed with newly npm install.
```
{"message":"Error ocurred in mock service: NoMethodError - undefined method `each' for #<String:0x2b913e8>","backtrace":["C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/request_decorator.rb:40:in `query'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/request_decorator.rb:20:in `as_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/interaction_decorator.rb:18:in `as_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_decorator.rb:18:in `block in as_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_decorator.rb:18:in `collect'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_decorator.rb:18:in `as_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_decorator.rb:26:in `to_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/json-2.0.3/lib/json/pure/generator.rb:242:in `generate'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/json-2.0.3/lib/json/common.rb:286:in `pretty_generate'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_writer.rb:66:in `pact_json'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_writer.rb:59:in `update_pactfile'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_writer.rb:52:in `update_pactfile_if_needed'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer_contract/consumer_contract_writer.rb:37:in `write'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/mock_service/request_handlers/pact_post.rb:31:in `respond'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.1/lib/rack/cascade.rb:33:in `block in call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.1/lib/rack/cascade.rb:24:in `each'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.1/lib/rack/cascade.rb:24:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/mock_service/app.rb:32:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/app/lib/pact/consumer/mock_service/set_location.rb:14:in `call'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'","C:/Projects/ei-site-api-debug/ei-site-api/src/node_modules/@pact-foundation/pact-mock-service-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
```

This error was introduced between 3 days ago to today. 
I compared the \node_modules\@pact-foundation\pact-node\package.json in two copies and find difference:
```
    "@pact-foundation/pact-mock-service": "0.10.x",
    "@pact-foundation/pact-provider-verifier": "0.1.x",
```
```
    "@pact-foundation/pact-mock-service": "1.x.x",
    "@pact-foundation/pact-provider-verifier": "1.x.x",
```
Having the same issue with pact version "pact": "2.3.4"
Could anyone please help have a look?

**Comment by mefellows** [comment] 2017-04-27 05:40
Hi @lippea,

Thanks for raising this. Could you please provide a test that we can use to reproduce the issue?

**Comment by lippea** [comment] 2017-04-27 05:44
Hi @mefellows I don't have a simple test to reproduce it at the moment. It happens in our real project testing. But just wondering should things keep the same if I use the same version of pact?

**Comment by mefellows** [comment] 2017-04-27 05:45
Downgrading to the previous versions of the two libraries you mention (in fact, in this case just the mock-service seems to be causing grief) should sort it out.

That being said, we'd love to know what's broken so that we can fix it!

**Comment by lippea** [comment] 2017-04-27 05:50
@mefellows thanks for help. I think I figured out why the versions changed while I was using the same pact version.
But I only refer to pact in my package.json. I tried to downgrade it to 2.20, it didn't work. The two libraries is referred inside pact-node, which is out of my control. And it's causing problem in CI build, which I can just modify it. I'm trying to fix it to unblock our main branch, so haven't got time to investigate what exactly caused the issue. Any recommendation for a fix?

**Comment by mefellows** [comment] 2017-04-27 05:51
You can override the versions of those libraries in your own `package.json` which will take precedence over the transitive dependencies declared in `pact-node`.

**Comment by lippea** [comment] 2017-04-27 05:54
@mefellows thanks. I'll give it a try now.

**Comment by lippea** [comment] 2017-04-27 05:56
Got another error:
```
ERROR: The process "21492" not found.
child_process.js:526
    throw err;
    ^

Error: Command failed: taskkill /f /t /pid 21492
ERROR: The process "21492" not found.

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Server.stop (C:\Projects\ei-site-api-debug\ei-site-api\src\node_modules\@pact-foundation\pact-node\src\server.js:138:7)
    at Server.<anonymous> (C:\Projects\ei-site-api-debug\ei-site-api\src\node_modules\@pact-foundation\pact-node\src\server.js:117:8)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by lippea** [comment] 2017-04-27 06:02
I got it through with adding "@pact-foundation/pact-node": "4.8.1",
Thanks @mefellows

**Comment by mefellows** [comment] 2017-04-27 07:03
Glad to hear you've got a workaround, if you get a moment we'd love an example so that we can reproduce and fix.

**Comment by joelgithub** [comment] 2017-05-10 11:03
I've also had this error. After some investigation it seemed to me that the problem is in the pact-mock_service and was introduced in 1.0.0 which corresponds to pact-node 4.8.2. Problem has to do with query parameter parsing of the pact dsl. From this version the query is supposed to be a map rather than a string as in previous versions. The code in lib/pact/consumer_contract/request_decorator.rb changed from:

```
def query
      if include_matching_rules?
        request.query
      else
        Pact::Reification.from_term(request.query)
      end
    end

```
to:
```

def query
      if include_matching_rules?
        request.query.query.each do | key, val |
          if val.length == 1
            request.query.query[key] = val[0]
          end
        end
        request.query.query
      else
        Pact::Reification.from_term(request.query)
      end
    end
```

It's this code that fails when the query is a string and not a map (the "each" part fails).

So this is actually fixable by changing all the queries in the interaction specs from something like this:
`query: "userId=123`
to this:
`query: { userId: 123 }`

HOWEVER!
This change makes the pact-js consumer tests work but on my provider side I use pact-jvm which does not accept the query as a map until spec version 3 so it will fail in the PactReader.loadPact method when trying to parse the query **string** since I'm using spec version 2.

So it seems to me that there is a spec-mismatch between pact-node and pact-jvm. I've been able to downgrade to pact-node 4.8.1 to get the < 1.0.0 version of pact-mock_service which is still compatible with pact-jvm's perception of spec version 2.

**Comment by mefellows** [comment] 2017-05-10 11:19
Thanks for the investigation on this @joelgithub!

@bethesque what are your thoughts?

**Comment by joelgithub** [comment] 2017-05-10 12:58
I also found a related problem that the metadata section of the pact generated by my pact-js consumer tests is not compatible with the way pact-jvm's PactReader.loadPact resolves the pact spec version.

This code in PactReader (from the master branch/latest version): 
```
 static Pact loadPact(Map options = [:], def source) {
    def pact = loadFile(source, options)
    def version = '2.0.0'
    def specification = pact.metadata?.'pact-specification'
    if (specification instanceof Map && specification.version) {
      version = specification.version
    }
    if (version == '3.0') {
        version = '3.0.0'
    }
    def specVersion = Version.valueOf(version)
    switch (specVersion.majorVersion) {
        case 3:
            return loadV3Pact(source, pact)
        default:
            return loadV2Pact(source, pact)
    }
  }
```

expects a metadata spec. version section that has this format:
```

"metadata": {
        "pact-specification": {
            "version": "x.x.x"
        }
```

BUT my pacts generated from pact-js generates a metadata section that looks like this:
```

"metadata": {
    "pactSpecificationVersion": "3.0.0"
  }
```

I discovered this when I tried to resolve the above issue by setting spec version to 3 in my pact-js environment thereby trying to make pact-jvm load the pact as a spec 3 pact. Because of this the pact is still loaded as a spec version 2 pact however.

**Comment by mefellows** [comment] 2017-05-10 13:10
Interesting, this is a problem in the upstream Ruby library (which also doesn't support v3). 

I've raised an [issue](https://github.com/realestate-com-au/pact/issues/137) over there and will keep this tracking issue until it's resolved.

**Comment by bethesque** [comment] 2017-05-10 22:20
The ruby code should handle both a map and a string. The `include_matching_rules` code was a PR written by someone who didn't understand that, and I merged it without considering that, sorry. I will fix it as soon as I can.

**Comment by bethesque** [comment] 2017-05-10 23:35
Ok, I've fixed the mock server. @mefellows can you update the JS mock server package to use pact-mock_service v 2.0.1 when you have time?

**Comment by mefellows** [comment] 2017-05-11 10:31
Will do - thanks @bethesque

**Comment by mefellows** [comment] 2017-05-11 10:50
Done: https://www.npmjs.com/package/@pact-foundation/pact-mock-service

`v2.0.1` released - I'll update Pact Node / Pact JS shortly.

**Comment by lippea** [comment] 2017-05-11 23:22
I'm glad the root cause is found. Thanks for fixing this. I can give a try in my project when the fix is ready.

**Comment by joelgithub** [comment] 2017-05-12 00:36
Yes thanks for the quick fixing! I to will verify as soon as I can.

**Comment by mefellows** [comment] 2017-05-12 02:35
`v2.4.2` just released, please let us know how you go!

**Comment by travi** [comment] 2017-05-12 03:14
with the following installed, i still appear to be getting the same error

```
├─┬ @pact-foundation/pact-node@4.9.1 
│ ├─┬ @pact-foundation/pact-mock-service@2.0.2 
│ │ └── @pact-foundation/pact-mock-service-darwin@2.0.2 
│ └─┬ @pact-foundation/pact-provider-verifier@1.1.1 
│   └── @pact-foundation/pact-provider-verifier-darwin@1.1.1 
```

**Comment by travi** [comment] 2017-05-12 03:21
nevermind. it looks like this project depends on `pact` as well as `@pact-foundation/pact-node`, so after updating to the latest version of `pact` as well, things are working.

thanks for getting this resolved!

**Comment by mefellows** [comment] 2017-05-12 04:22
Great! FWIW any project using a recent `pact` should automatically bring in
the pact-dev dependency.

**Comment by mefellows** [comment] 2017-05-12 10:17
I'll wait for @lippea and @joelgithub to respond before closing, but it looks like a promising start!

**Comment by joelgithub** [comment] 2017-05-12 11:00
It seems that both the map and string versions of the query is now supported so that solves my problem for now. I gather from reading the [issue](https://github.com/realestate-com-au/pact/issues/137) that the specification version syntax in the pact metadata is still to be decided and implemented in pact-jvm (and possibly elsewhere)? It doesn't hurt me right now though.
Thanks for the quick action @mefellows & @bethesque!

**Comment by mefellows** [comment] 2017-05-14 06:02
Thanks for confirming! I'm going to close this issue and re-open a separate one for the metadata problem.

**Closed by mefellows** 2017-05-14 06:02 UTC
Labels: bug

**Comment by lippea** [comment] 2017-05-21 22:44
After upgrading the pact version to "2.4.2", it looks fine in my project. Thanks for the fix @mefellows
